config/routes.rb
Rails.application.routes.draw do
  
  root to: 'homes#top'
  devise_for :users
  get 'home' => "posts#index"
  post "tags/:id/follow_tags" => "follow_tags#create", as: "follow_tags"
  delete "tags/:id/follow_tags" => "follow_tags#destroy", as: "follow_tag"
  get "tags/ranking" => "tags#rank", as: "tags_rank"
  get '/posts/tag/:tag' => 'posts#tag', as: 'tag'
  get "search" => "search#search"
  resources :users, only: [:show, :edit, :update]
  resources :tags, only: [:index]
  resources :posts, only: [:create, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow_tag.rb
class FollowTag < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :image
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def save_tags(tag_list)
    tag_list.each do |tag|
      target_tag = Tag.find_by(name:tag)
      if  target_tag
        PostTag.create!({post_id:self.id,tag_id:target_tag.id})
      else
        created_tag = Tag.create!(name:tag)
        PostTag.create!({post_id:self.id,tag_id:created_tag.id})
      end
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  before_save :downcase_name
  
  validates :name, presence: true, length: { maximum: 30 }
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  has_many :follow_tags, dependent: :destroy
  has_many :users, through: :follow_tags
  
  private

    def downcase_name
      self.name.downcase!
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follow_tags, dependent: :destroy
  has_many :tags, through: :follow_tags
  attachment :profile_image
         
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  
  
  
  validates :nickname, presence: true, length: { maximum: 20 }
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }, format: { with: VALID_PASSWORD_REGEX }, on: :create
  
  
  
  def followed?(tag)
    tags.where(id: tag.id).exists?
  end
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    if comment.save
      redirect_to post_path(post)
    else
      redirect_to request.referer
      flash[:comment_error] = "コメントが入力されていません"
    end
  end
  
  def destroy
    Comment.find_by(id: params[:id]).destroy
    redirect_to post_path(params[:post])
  end
  
  
  private
  
  def comment_params
    params.require(:comment).permit(:body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :baria_post, only: [:destroy]
    
    def create
      @new_post = Post.new(post_params)
      @new_post.user_id = current_user.id
      tag_list = tag_params[:names].split(/[[:blank:]]+/).select(&:present?)
      if (tag_list.length > 0) && @new_post.save
        @new_post.save_tags(tag_list)
        redirect_to post_path(@new_post.id)
      else
        redirect_to request.referer
        flash[:"alert-danger"] = "タグの入力は必須です"
      end
    end
    
    def index
      @posts = Post.joins(:post_tags).where(post_tags: {tag_id: current_user.tags.ids}).order(created_at: :desc).uniq
      @tag_post_ranks = Tag.find(PostTag.group(:tag_id).order('count(tag_id)desc').limit(5).pluck(:tag_id))
    end
    
    def show
      @post = Post.find(params[:id])
      @comment = Comment.new
      @tags = @post.tags
    end
    
    def tag
      @posts = Tag.find_by(name: params[:tag]).posts.order(created_at: :desc)
      @tag = Tag.find_by(name: params[:tag])
    end
    
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to home_path
    end
    
    private
    
    def post_params
      params.require(:post).permit(:body, :image, :tagbody)
    end
    
    def tag_params
      params.require(:post).permit(:names)
    end
    
    def baria_post
      unless Post.find(public[:id]).user.id.to_i == current_user.id
        flash[:notice] = "権限がありません"
        redirect_to home_path
      end
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @posts = Post.joins(:tags).where(tags:{ name: "#{params[:keyword]}"}).distinct.order(created_at: :desc)
    @tag = Tag.find_by(name: params[:keyword])
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def index
    @tags = Tag.order("name")
  end
  
  def rank
    @tag_post_ranks = Tag.find(PostTag.group(:tag_id).order('count(tag_id)desc').limit(5).pluck(:tag_id))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :baria_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  
  private

  def user_params
    params.require(:user).permit(:name, :nickname, :introduction, :profile_image)
  end
  
  def baria_user
    if current_user.id != params[:id].to_i
      flash[:notice]="編集権限がありません"
      redirect_to user_path(params[:id])
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_posts.html.erb
<div class="post-box">
  <% posts.each do |post| %>
    <section class="container post-item">
      <%= link_to post_path(post.id) do %>
      <object>
        <div class="row post-head">
          <div class="col post-user">
            <%= link_to user_path(post.user) do %>
              <%= attachment_image_tag post.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_imagesan.png", class: "user-image" %>
              <%= post.user.nickname %>
            <% end %>
          </div>
          <div class="col post-created_at">
            <%= post.created_at.strftime('%Y/%m/%d') %>
          </div>
          <div class="col-6 post-tags">
            <span>
              <% post.tags.each do |tag| %>
                <%= link_to tag_path(tag.name) do %>
                  　<%= tag.name %>
                <% end %>
              <% end %>
            </span>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <p><%= post.body %></p>
            <%= attachment_image_tag post, :image, class: "thumb_300" %></br>
          </div>
        </div>
        <div class="row reactions">
          <div class="col-2 favorite">
            <% if post.favorited_by?(current_user) %>
              <span>
                <%= link_to post_favorites_path(post), method: :delete do %>
                  <i class="fas fa-heart heart"></i><%= post.favorites.count %>
                <% end %>
              </span>
              <% else %>
              <span>
                <%= link_to post_favorites_path(post), method: :post do %>
                  <i class="far fa-heart heart"></i><%= post.favorites.count %> 
                <% end %>
              </span>
            <% end %>
          </div>
          <div class="col-3">
            <span>
              <i class="far fa-comment"></i><%= post.comments.count  %>
            </span>
          </div>
          <div class="col-7 post-destroy-btn">
            <% if post.user == current_user %>
              <%= link_to post_path(post), method: :delete do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </object>
      <% end %>
    </section>
  <% end %>
</div>

app/views/posts/index.html.erb
<% if @posts.present? %>
  <%= render 'posts/posts', posts: @posts %>
<% else %>
  <div class="container">
    <h2>タグをフォローしてみましょう！</h2>
    <h3>投稿の多いタグランキング</h3>
    <table>
      <% @tag_post_ranks.each.with_index(1) do |tag,i| %>
        <tr>
          <th class="rank-tag-num">
            第<%= i %>位
          </th>
          <td>
            <%= link_to tag_path(tag.name) do %>
              <div class="rank-tag"><%= tag.name%></div>
            <% end %>
          </td>
          <td>
            <% if current_user.followed?(tag) %>
              <div class="dropdown">
                <button class="btn dropdown-toggle following-drop btn-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  フォロー中
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="#">
                    <%= link_to "フォロー解除", follow_tag_path(tag), method: :delete %>　<!--ハッシュタグのフォロー解除-->
                  </a>
                </div>
              </div>
            <%else%>
              <div class="following-tag-follow-btn">
                <%= link_to "フォローする", follow_tags_path(tag), method: :post , class: "follow-btn btn btn-white"%>　<!--ハッシュタグのフォロー-->
              </div>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>なんの話する？</h1>
<%= form_with model: @new_post, local:true do |f| %>
  <h4>ハッシュタグ</h4>
  <%= f.text_area :hashbody, size:"55x3" %>
  <h4>本文</h4>
  <%= f.text_field :body %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <%= f.submit '投稿' %>
<% end %>
  

app/views/posts/show.html.erb
<div class="post-box">
  <section class="container post-item">
    <div class="row post-head">
      <div class="col post-user">
        <%= attachment_image_tag @post.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_imagesan.png", class: "user-image" %>
        <%= @post.user.nickname %>
      </div>
      <div class="col post-created_at">
        <%= @post.created_at %>
      </div>
      <div class="col-6 post-tags">
        <span>
          <% @post.tags.each do |tag| %>
            <%= link_to tag_path(tag.name) do %>
              　<%= tag.name %>
            <% end %>
          <% end %>
        </span>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <p><%= @post.body %></p>
        <div class="post-image">
          <%= attachment_image_tag @post, :image, width: '500' %></br>
        </div>
      </div>
    </div>
    <div class="row reactions">
      <div class="col-2 favorite">
        <% if @post.favorited_by?(current_user) %>
          <span>
            <%= link_to post_favorites_path(@post), method: :delete do %>
              <i class="fas fa-heart heart"></i><%= @post.favorites.count %>
            <% end %>
          </span>
          <% else %>
          <span>
            <%= link_to post_favorites_path(@post), method: :post do %>
              <i class="far fa-heart heart"></i><%= @post.favorites.count %> 
            <% end %>
          </span>
        <% end %>
      </div>
      <div class="col-3">
        <span>
          <i class="far fa-comment"></i><%= @post.comments.count  %>
        </span>
      </div>
      <div class="col-7 post-destroy-btn">
        <% if @post.user == current_user %>
          <%= link_to post_path(@post), method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
  <div class=" post-comment-zone">
    <div class="post-comment-form">
      <%= form_with(model:[@post, @comment], local: true) do |f| %>
        <%= f.text_field :body, rows:'5',placeholder: "コメントをここに" %>
        <%= f.submit "送信する" %>
        <%= flash[:comment_error] %>
      <% end %>
    </div>
    <div class="post-comments">
      <% @post.comments.each do |comment| %>
        <div class="post-comment">
          <%= attachment_image_tag comment.user, :profile_image, size: "30x30", format: 'jpeg', fallback: "no_imagesan.png", class: "user-image" %>
          <%= comment.user.name %>
          <%= comment.created_at.strftime('%Y/%m/%d') %></br>
          <%= comment.body %>
          <% if comment.user == current_user %>
            <div>
              <%= link_to "削除", post_comment_path(comment.post, comment), method: :delete %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/tag.html.erb
<h1>「<%= @tag.name %>」の投稿一覧</h1>
<% if current_user.followed?(@tag) %>
  <div class="dropdown">
    <button class="btn dropdown-toggle following-drop btn-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      フォロー中
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="#">
        <%= link_to "フォロー解除", follow_tag_path(@tag), method: :delete %>　<!--ハッシュタグのフォロー解除-->
      </a>
    </div>
  </div>
<%else%>
  <div class="following-tag-follow-btn">
    <%= link_to "フォローする", follow_tags_path(@tag), method: :post , class: "follow-btn btn btn-white"%>　<!--ハッシュタグのフォロー-->
  </div>
<% end %>

<%= render 'posts/posts', posts: @posts %>

app/views/tags/index.html.erb
<h2>タグ一覧</h2>
<% @tags.each do |tag| %>
  <%= link_to tag_path(tag.name) do %>
    <span>・<%= tag.name %></span>
  <% end %>
<% end %>

<%= link_to tags_rank_path do %>
  <h3>人気のタグランキングはこちら</h3>
<% end %>

app/views/tags/rank.html.erb
<div class="container">
    <h3>投稿の多いタグランキング</h3>
    <table>
      <% @tag_post_ranks.each.with_index(1) do |tag,i| %>
        <tr>
          <th class="rank-tag-num">
            第<%= i %>位
          </th>
          <td>
            <%= link_to tag_path(tag.name) do %>
              <div class="rank-tag"><%= tag.name%></div>
            <% end %>
          </td>
          <td>
            <% if current_user.followed?(tag) %>
              <div class="dropdown">
                <button class="btn dropdown-toggle following-drop btn-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  フォロー中
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="#">
                    <%= link_to "フォロー解除", follow_tag_path(tag), method: :delete %>　<!--ハッシュタグのフォロー解除-->
                  </a>
                </div>
              </div>
            <%else%>
              <div class="following-tag-follow-btn">
                <%= link_to "フォローする", follow_tags_path(tag), method: :post , class: "follow-btn btn btn-white"%>　<!--ハッシュタグのフォロー-->
              </div>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model:@user, local: true do |f| %>
  <table>
    <tr>
      <th>
        <label for="inputNickName">名前</label>
      </th>
      <td>
        <%= f.text_field :nickname, autofocus: true, id:"inputNickName", placeholder:"ニックネーム" %>
      </td>
    </tr>
    <tr>
      <th>
        <label for="inputIntroduction">自己紹介</label>
      </th>
      <td>
        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介", size: "30x3" %>
      </td>
    </tr>
    <tr>
      <th></th>
      <td>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </td>
    </tr>
    <tr>
      <th></th>
      <td>
        <%= f.submit "変更を保存" %>
      </td>
    </tr>
  </table>
<% end %>

app/views/users/show.html.erb
<div class="container profile-box">
  
  <div class="col-4">
    <%= attachment_image_tag @user, :profile_image, size: "180x180", format: 'jpeg', fallback: "no_imagesan.png", class: "user-image" %>
  </div>
  
  <div class="col-4 profile-intros">
    <div class="container">
      <div class="row">
        <p class="user-show-name"><%= @user.nickname %></p>
      </div>
      <div class="row">
        <p><%= @user.introduction %></p>
      </div>
    </div>
  </div>
  
  <div class="col-4">
    <div class="container">
      <div class="row">
        <!-- Button trigger modal -->
        <button type="button" class="btn" data-toggle="modal" data-target="#exampleModalLong">
          フォロー中のタグ<%= @user.tags.count %>個
        </button>
        
        <!-- Modal -->
        <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">フォロー中のタグ一覧</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <% @user.tags.each do |tag| %>
                  <div class="row following-tag">
                    <span class="col following-tag-name">
                      <%= link_to tag_path(tag.name) do %>
                        　<%= tag.name %>
                      <% end %>
                    </span>
                    <span class="col">
                      <% if current_user.followed?(tag) %>
                        <div class="dropdown">
                          <button class="btn dropdown-toggle following-drop" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            フォロー中
                          </button>
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">
                              <%= link_to "フォロー解除", follow_tag_path(tag), method: :delete %>　<!--ハッシュタグのフォロー解除-->
                            </a>
                          </div>
                        </div>
                      <%else%>
                        <div class="following-tag-follow-btn">
                          <%= link_to "フォローする", follow_tags_path(tag), method: :post , class: "follow-btn btn"%>　<!--ハッシュタグのフォロー-->
                        </div>
                      <% end %>
                    </span>
                  </div>
                <% end %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row post-count">
        <span>
          投稿<%= @user.posts.count %>件
        </span>
      </div>
    </div>
  </div>
</div>

<%= render 'posts/posts', posts: @posts %>