config/routes.rb
Rails.application.routes.draw do
  
  root to: 'homes#top'
  devise_for :users
  get 'home' => "posts#index"
  post "tags/:id/follow_tags" => "follow_tags#create", as: "follow_tags"
  delete "tags/:id/follow_tags" => "follow_tags#destroy", as: "follow_tag"
  get "tags/ranking" => "tags#rank", as: "tags_rank"
  get '/posts/tag/:tag' => 'posts#tag', as: 'tag'
  get "search" => "search#search"
  resources :users, only: [:show, :edit, :update]
  resources :tags, only: [:index]
  resources :posts, only: [:create, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow_tag.rb
class FollowTag < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :image
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def save_tags(tag_list)
    tag_list.each do |tag|
      target_tag = Tag.find_by(name:tag)
      if  target_tag
        PostTag.create!({post_id:self.id,tag_id:target_tag.id})
      else
        created_tag = Tag.create!(name:tag)
        PostTag.create!({post_id:self.id,tag_id:created_tag.id})
      end
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  before_save :downcase_name
  
  validates :name, presence: true, length: { maximum: 30 }
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  has_many :follow_tags, dependent: :destroy
  has_many :users, through: :follow_tags
  
  private

    def downcase_name
      self.name.downcase!
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follow_tags, dependent: :destroy
  has_many :tags, through: :follow_tags
  attachment :profile_image
         
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  
  
  
  validates :nickname, presence: true, length: { maximum: 20 }
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }, format: { with: VALID_PASSWORD_REGEX }, on: :create
  
  
  
  def followed?(tag)
    tags.where(id: tag.id).exists?
  end
 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :baria_post, only: [:destroy]
    
    def create
      @new_post = Post.new(post_params)
      @new_post.user_id = current_user.id
      tag_list = tag_params[:names].split(/[[:blank:]]+/).select(&:present?)
      if (tag_list.length > 0) && @new_post.save
        @new_post.save_tags(tag_list)
        redirect_to post_path(@new_post.id)
      else
        redirect_to request.referer
        flash[:"alert-danger"] = "タグの入力は必須です"
      end
    end
    
    def index
      @posts = Post.joins(:post_tags).where(post_tags: {tag_id: current_user.tags.ids}).order(created_at: :desc).uniq
      @tag_post_ranks = Tag.find(PostTag.group(:tag_id).order('count(tag_id)desc').limit(5).pluck(:tag_id))
    end
    
    def show
      @post = Post.find(params[:id])
      @comment = Comment.new
      @tags = @post.tags
    end
    
    def tag
      @posts = Tag.find_by(name: params[:tag]).posts.order(created_at: :desc)
      @tag = Tag.find_by(name: params[:tag])
    end
    
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to home_path
    end
    
    private
    
    def post_params
      params.require(:post).permit(:body, :image, :tagbody)
    end
    
    def tag_params
      params.require(:post).permit(:names)
    end
    
    def baria_post
      unless Post.find(public[:id]).user.id.to_i == current_user.id
        flash[:notice] = "権限がありません"
        redirect_to home_path
      end
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def index
    @tags = Tag.order("name")
  end
  
  def rank
    @tag_post_ranks = Tag.find(PostTag.group(:tag_id).order('count(tag_id)desc').limit(5).pluck(:tag_id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tagren</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="body-container">
      <heder class="header">
        <div class="container">
          <nav class="navbar">
            <div class="container">
              <div class="navbar-brand logo">
                <span class="logo-icon"><%= image_tag'logobean.png', size: '60x60' %></span>
                <span class="logo-name"><h2 class="tagren">Tagren</h2></span>
              </div>
              <div class="navbar-items">
                <% if user_signed_in? %>
                  <div class="search-form">
                    <%= form_with url: search_path, method: :get, local: true do |f| %>
                      <%= f.text_field :keyword, placeholder: "タグで検索"  %>
                      <%= f.submit "検索" %>
                    <% end %>
                  </div>
                  <div class="home-btn">
                    <%= link_to home_path do %>
                      <i class="fas fa-home fa-2x"></i>
                    <% end %>
                  </div>
                  <div class="tags-btn">
                    <%= link_to tags_path do %>
                      <i class="fas fa-tags fa-lg"></i>
                    <% end %>
                  </div>
                  <div class="post-btn">
                    <!-- Button trigger modal -->
                    <button type="button" class="btn" data-toggle="modal" data-target="#exampleModal" >
                      <i class="far fa-plus-square fa-2x"></i>
                    </button>
                    
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">投稿を作成</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <%= form_with model: Post.new, local:true do |f| %>
                            <div class="modal-body">
                              <h4>なんの話する？</h4>
                              <%= f.text_field :names, placeholder: "タグを入力" %><span>スペースで複数のタグを設定可能です</span>
                              <%= f.text_field :body, size: "40", placeholder: "キャプションを入力", class: "post-form-body" %>
                              <h4>画像</h4>
                              <%= f.attachment_field :image %>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                              <button type="submit" class="btn btn-primary">投稿する</button>
                            </div>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="dropdown">
                    <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <%= attachment_image_tag current_user, :profile_image, size: "35x35", format: 'jpeg', fallback: "no_imagesan.png", class: "user-image" %><span class="user-name"><%= current_user.nickname %></span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="#"><%= link_to "マイページ", user_path(current_user) %></a>
                      <a class="dropdown-item" href="#"><%= link_to "プロフィール編集", edit_user_path(current_user) %></a>
                      <a class="dropdown-item" href="#"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></a>
                    </div>
                  </div>
                <% else %>
                  <p>
                    <%= link_to "新規登録", new_user_registration_path %>　<%= link_to "ログイン", new_user_session_path %>
                  </p>
                <% end %>
              </div>
            </div>
          </nav>
        </div>
      </heder>
      <main>
        <div class="container">
          <% flash.each do |key, value| %>
            <%= content_tag(:p, value, class: "alert #{key}") %>
          <% end %>
          <%= yield %>
        </div>
      </main>
      <footer></footer>
    </div>
  </body>
</html>